{{- if .Values.webhook.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-secrets.fullname" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "external-secrets-webhook.labels" . | nindent 4 }}
    external-secrets.io/component : webhook
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: {{ .Values.webhook.port }}
    protocol: TCP
    name: webhook
  selector:
    {{- include "external-secrets-webhook.selectorLabels" . | nindent 4 }}
{{- end }}